import type { Metadata } from "next";
import { Old_Standard_TT } from "next/font/google";
import "./globals.css";

const oldStandard = Old_Standard_TT({
  weight: ['400', '700'],
  variable: "--font-old-standard-tt",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oldStandard.className}`}
      >
        {children}
      </body>
    </html>
  );
}
